title: "Barry Cheng â€” Portfolio"
description: "Selected musical and technical work."
# Use a built-in GitHub Pages Jekyll theme:
theme: jekyll-theme-cayman

# Optional: basic site metadata
author: "Barry Cheng"
github_username: barry-mir
